name: Deploy to Surge.sh

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to Surge.sh
        run: |
          npm install -g surge
          surge ./ --domain 1erparcialelectiva2.surge.sh --token ${{ secrets.SURGE_TOKEN }}